### ISSUE TITLE
docs: add documentation site

### ISSUE THREAD

**Issue by jonathanwalter** [Eyevinn/autovmaf-api#43]
We should add proper documentation, like the [Channel Engine](https://github.com/Eyevinn/channel-engine) project: https://vod2live.docs.eyevinn.technology/

Should be made with https://www.mkdocs.org/

**Comment by birme** [comment]
I have prepared a repo and mkdocs setup to start from: https://github.com/Eyevinn/autovmaf-docs

**Comment by jonathanwalter** [comment]
Done! https://autovmaf.docs.eyevinn.technology/
